version: '3.8'
services:
  postgres:
    container_name: ts_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ft_trans
    ports:
      - "5432:5432"
  nginx:
    container_name: ts_nginx
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
            - ./frontend/build:/usr/share/nginx/html
  node:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    container_name: ts_node
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
