version: '3.8'
services:
  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ft_trans
    ports:
      - "5432:5432"
  nginx:
      container_name: ts_nginx
      build:
        context: ./frontend/.
        dockerfile: Dockerfile
      ports:
        - "3006:80"
      restart: always
  node:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    container_name: ts_node
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"